name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update README with Latest Medium Blogs
      run: |
        MEDIUM_USERNAME="kevinkiarie7"
        REPO_NAME="https://github.com/KingKiarie/KingKiarie.git"
        README_PATH="README.md"
        
        BLOG_DATA=$(curl -s "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@$MEDIUM_USERNAME")
        
        BLOG_TITLES=($(echo "$BLOG_DATA" | jq -r '.items[].title'))
        BLOG_URLS=($(echo "$BLOG_DATA" | jq -r '.items[].link'))
        
        echo "Last updated: $(date)" > "$README_PATH"
        echo "<!-- Latest Medium Blogs -->" >> "$README_PATH"
        echo "<div align=\"center\">" >> "$README_PATH"
        echo "  <h3>Latest Medium Blogs</h3>" >> "$README_PATH"
        echo "  <ul>" >> "$README_PATH"
        
        for ((i=0; i<${#BLOG_TITLES[@]}; i++)); do
          echo "    <li><a href=\"${BLOG_URLS[$i]}\">${BLOG_TITLES[$i]}</a></li>" >> "$README_PATH"
        done
        
        echo "  </ul>" >> "$README_PATH"
        echo "</div>" >> "$README_PATH"

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add "$README_PATH"
        git commit -m "Update README with latest Medium blogs [skip ci]"
        git push

  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
