name: Update README and Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Latest Medium Blogs and Update README
        run: |
          MEDIUM_USERNAME="kevinkiarie7"
          BLOG_DATA=$(curl -s "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@$MEDIUM_USERNAME")
          BLOG_TITLES=($(echo "$BLOG_DATA" | jq -r '.items[].title' | head -5))
          BLOG_URLS=($(echo "$BLOG_DATA" | jq -r '.items[].link' | head -5))
          BLOG_LIST=""
          for ((i=0; i<${#BLOG_TITLES[@]}; i++)); do
            BLOG_LIST+="- [${BLOG_TITLES[$i]}](${BLOG_URLS[$i]})\n"
          done
          sed -i "/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n$BLOG_LIST<!-- BLOG-POST-LIST:END -->" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update README with latest Medium blogs [skip ci]"
          git push

  generate-snake-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
